# Generated by Django 4.1.3 on 2022-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('en', 'en'), ('ar', 'ar'), ('fr', 'fr')], default='en', max_length=13)),
                ('category', models.CharField(blank=True, choices=[('last', 'last'), ('local', 'local'), ('international', 'international'), ('sport', 'sport')], default='last', max_length=13)),
                ('title', models.TextField(max_length=150)),
                ('creation_datetime', models.DateTimeField(auto_now=True)),
                ('img_1', models.ImageField(upload_to='images/%y/&m/%d')),
                ('img_2', models.ImageField(upload_to='images/%y/&m/%d')),
                ('img_3', models.ImageField(upload_to='images/%y/&m/%d')),
                ('details', models.TextField(max_length=1000)),
            ],
        ),
    ]
