# Generated by Django 4.1.3 on 2022-12-01 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_news_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRegisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.BooleanField(default=True)),
                ('local', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=False)),
                ('sport', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdeia_url', models.ImageField(upload_to='images/%y/&m/%d')),
                ('media_type', models.CharField(choices=[('Image', 'image'), ('Audio', 'audio'), ('Video', 'video'), ('NoMedia', 'nomedia')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='new',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='new',
            name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='new',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='new',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='img_3',
        ),
        migrations.AddField(
            model_name='new',
            name='FB_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='Thumb',
            field=models.FileField(default='d', upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='ispublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='platform',
            field=models.CharField(choices=[('en', 'en'), ('ar', 'ar'), ('fr', 'fr')], default='ios', max_length=7),
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('Modifiedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modify_relation', to=settings.AUTH_USER_MODEL)),
                ('createby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='new',
            name='media',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='app.media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
